### ISSUE TITLE
The claycrafter will keep working even if full.

### ISSUE THREAD

**Issue by Dragonop** [Dragonop/claycrafter#5]
The claycrafter will keep using up the glasses of water and the compressed dirt even if the output slots are full.
@everamzah

**Comment by ghost** [comment]
Okie dokie, lemme take a look-see.

**Comment by ghost** [comment]
I got as far as I could.  Take a good look at what the code says and try to finesse it out.  It's still working even though it's full, but won't subtract or add anything if it is.

**Comment by Dragonop** [comment]
That kinda fixes it, still, the glasses of water will be used even if it's not possible to make more clay and as you said,  It's still working even if full, I will try to fix that. Thanks everamzah.

**Comment by Dragonop** [comment]
https://github.com/Dragonop/claycrafter/commit/8d7c5f68e5f18314f2ee9cf1fdc816e642df1c3b
It still won't replace claycrafter_active with claycrafter.
And now when there  is only one spot left, and there is dirt and water inside fuel and src, it will give the drinking glass but not the clay, but, it will still substract dirt.
I believe the problem is from L192 to L199

@everamzah what do you think about adding a separate inventory for vessels:drinking_glass? I think that might solve most problems.

**Comment by Dragonop** [comment]
@everamzah what do you think about adding a separate inventory for vessels:drinking_glass? I think that might solve most problems.

**Comment by ghost** [comment]
oh well now we're getting fancy.

**Comment by ghost** [comment]
An extra inventory for vessels and stuff is getting fancy, and I think there's plenty one can do with this, and indeed its parent furnace!  So, and I can't believe I didn't think of thing earlier, but the vessels just go back into player inv, and if full drop onto floor.

**Comment by Dragonop** [comment]
We can't make the vessel just go back into the player inv, that would be like teleporting the items there, and that doesn't makes sense

**Comment by ghost** [comment]
Oh ya, didn't think of that.  An extra inventory list sounds find.

`local meta = minetest.get_meta(pos)`
`local inv = meta:get_inventory()`
`inv:set_size("vessels", 2*2)`

**Comment by ghost** [comment]
@Dragonop I probably placed this comment in the wrong place. This is how you create an inventory.  After it's made, access it with list[].
