### ISSUE TITLE
glass of water lacks vessels group rating

### ISSUE THREAD

**Issue by ghost** [Dragonop/claycrafter#7]
https://github.com/minetest/minetest_game/blob/master/mods/vessels/init.lua#L126
https://github.com/minetest/minetest_game/blob/master/mods/vessels/init.lua#L55

**Comment by Dragonop** [comment]
https://github.com/Dragonop/claycrafter/commit/7a8d7ea8c6b7ebab0a5a03ae918fcf2040ccb966

**Comment by Dragonop** [comment]
This could be useful if we do the inventory in the claycrafter for vessels
