### ISSUE TITLE
The claycrafter won't change from active to inactive

### ISSUE THREAD

**Issue by Dragonop** [Dragonop/claycrafter#9]
The claycrafter won't change from claycrafter:claycrafter_active to claycrafter:claycrafter even if the output slots are full as long as there is water and dirt inside. It won't consume anything if the output is full.

**Comment by ghost** [comment]
Did you look in the ABM function?  That should be where it takes place.  So just have to figure out what in there is restricted the swap.

**Comment by ghost** [comment]
Line 269 of claycrafter.lua might be worth looking at.  I think it's looking for an old variable that was renamed.

**Comment by Dragonop** [comment]
Yes, I'm looking near that lines already, I don't think it's an old variable because it is based of furnace.lua. Still, I'm checking from line 250 to the end, also reworking the infotext to show how many dirt/water there is instead of using percentages.

**Comment by Dragonop** [comment]
Fixed in 4a8a178800fbdc98a30e7e61fd09d040dae810e3
